### ISSUE TITLE
MayhemDuck 1.4: illegal move

### ISSUE THREAD

**Issue by twoplan** [SamuraiDangyo/mayhem#4]
Thank you for MayhemDuck chess engine! It's a lot of fun to play against. 

In the following position, the black king is in check, but did castle. Isn't this illegal in duck chess too?!

<img width="609" alt="Screenshot_20221117_114901" src="https://user-images.githubusercontent.com/7384966/202428476-c1af6e1d-9b60-475b-aa46-5a9a4a7a08d1.png">

**Comment by SamuraiDangyo** [comment]
Hello. 
Thanks for testing MayhemDuck. 
I think it's ok. In the above position castling is legal since there's no checks in Duck Chess. King is captured.
Castling while in check is ok. If there's nothing between king and rook.

**Comment by twoplan** [comment]
This makes sense, thanks for looking into!
